In [2]:
import numpy as np

In [2]:
n1 = np.array([10, 20, 30 ,40])

In [3]:
n2 = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [4]:
n1

array([10, 20, 30, 40])

In [5]:
n2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [6]:
type(n1)

numpy.ndarray

In [7]:
type(n2)

numpy.ndarray

In [8]:
n3 = np.zeros((1, 2), dtype = int)

In [9]:
n3

array([[0, 0]])

In [10]:
n4 = np.full((2,3), 3)

In [11]:
n4

array([[3, 3, 3],
       [3, 3, 3]])

In [12]:
n4.shape

(2, 3)

In [13]:
n4.shape = (3,2)
n4

array([[3, 3],
       [3, 3],
       [3, 3]])

In [14]:
n2.shape

(2, 4)

In [15]:
n2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [16]:
n2.shape = (4,2)

In [17]:
n2

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

### Stacking of arrays

In [52]:
n5 = np.array([10,20,30])
n6 = np.array([30,40,60])

In [57]:
np.concatenate((n5, n6))

array([10, 20, 30, 30, 40, 60])

In [19]:
np.vstack((n5, n6))

array([[10, 20, 30],
       [30, 40, 60]])

In [20]:
n7 = np.array([1, 5, 3])
n8 = np.array([3, 6])

In [21]:
np.hstack((n7, n8))

array([1, 5, 3, 3, 6])

In [22]:
np.column_stack((n5, n6))

array([[10, 30],
       [20, 40],
       [30, 60]])

In [23]:
n9 = np.array([10,20,30, 40, 50, 60])
n0 = np.array([40, 50, 60, 70, 80, 90])

### Finding intersection and unqiue elements in arrays

In [24]:
# Common element between both the elements. (Intersection)

np.intersect1d(n9, n0) 

array([40, 50, 60])

In [25]:
# Elements that are unqiue to first array

np.setdiff1d(n9, n0)

array([10, 20, 30])

In [26]:
# Elements that are unqiue to first array

np.setdiff1d(n0, n9)

array([70, 80, 90])

### Addition operation on array: columns and row operations

In [27]:
# Total Addition
n9 = np.array([10,20,30, 40, 50, 60])
n0 = np.array([40, 50, 60, 70, 80, 90])

np.sum([n0, n9])

600

In [28]:
# Addition along the column

np.sum([n9, n0], axis = 0)

array([ 50,  70,  90, 110, 130, 150])

In [29]:
# Addition along the row

np.sum([n9, n0], axis = 1)

array([210, 390])

### Mathematical Scalar Operations

In [30]:
n1 = np.array([10, 20, 30 ,40])

In [31]:
# Addition 
n1 = n1 + 1
n1

array([11, 21, 31, 41])

In [32]:
# Subtraction
n1 = n1 -1
n1

array([10, 20, 30, 40])

In [33]:
# Mulltiplication
n1 = n1*2
n1

array([20, 40, 60, 80])

In [34]:
# Division
n1 = n1/2
n1

array([10., 20., 30., 40.])

In [35]:
n1 = np.array([10, 20, 30 ,40])

### Mean, Median and Standard Deviation

In [36]:
np.mean(n1)

25.0

In [37]:
np.std(n1)

11.180339887498949

In [38]:
np.median(n1)

25.0

### Extraction of elements

In [40]:
n1 = np.array([[1,2,3,4], [4,5,6,7], [7,8,9,10],[9,10,11,12]])
n1

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [ 9, 10, 11, 12]])

In [4]:
# Extraction of entire row (first)
n1[0]

array([1, 2, 3])

In [32]:
n1.shape

(3, 3)

In [45]:
# Extraction of entire column (third)
n1[2:4,2:5]

array([[ 9, 10],
       [11, 12]])

In [42]:
# Extracting elements of the matrix: You have to mention first row number and then column number
n1[0][2]

3

### Transpose

In [43]:
n1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
n1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Multiplication (Dot Product: Matrix * Matrix)

In [58]:
n1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
n2 = np.array([[4,5,6], [5,6,7], [6, 3, 4]])
n1, n2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[4, 5, 6],
        [5, 6, 7],
        [6, 3, 4]]))

In [60]:
np.concatenate((n1, n2), axis =1)

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 5, 6, 7],
       [7, 8, 9, 6, 3, 4]])

In [46]:
n1*n2

array([[ 4, 10, 18],
       [20, 30, 42],
       [42, 24, 36]])

In [47]:
# Dot Product

n1.dot(n2)

array([[ 32,  26,  32],
       [ 77,  68,  83],
       [122, 110, 134]])

In [48]:
n2.dot(n1)

array([[ 66,  81,  96],
       [ 78,  96, 114],
       [ 46,  59,  72]])

### Saving and Loading Numpy Array

In [49]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
np.save('array_file',n1)

In [51]:
n2 = np.load('array_file.npy')
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])