In [1]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [4]:
a = tf.constant([[1,2],
                 [3,4]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [5]:
b = tf.Variable([[1,2],
                 [3,4]])
b

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [7]:
AB = tf.concat(values = [a,b], axis = 0)
AB

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])>

In [8]:
AB = tf.concat(values = [a,b], axis = 1)
AB

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 1, 2],
       [3, 4, 3, 4]])>

In [11]:
t = tf.zeros(shape = (2,3), dtype = tf.int32)
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [15]:
o = tf.ones(shape = (2,3), dtype = tf.int32)
o

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [17]:
v = tf.constant(5, shape=(3,2))
v

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 5],
       [5, 5],
       [5, 5]])>

In [18]:
reshaped_ab =  tf.reshape(AB, shape = [4,2])
reshaped_ab

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])>

In [25]:
c = tf.random.uniform(shape=(3,5), maxval = 100, dtype = tf.int32)
c

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[69, 84, 97, 29, 54],
       [88, 16, 75, 18, 84],
       [32, 21, 50, 90, 31]])>

In [26]:
d = tf.cast(c, dtype = tf.float32)
d

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[69., 84., 97., 29., 54.],
       [88., 16., 75., 18., 84.],
       [32., 21., 50., 90., 31.]], dtype=float32)>

In [29]:
a = tf.transpose(d)
a

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[69., 88., 32.],
       [84., 16., 21.],
       [97., 75., 50.],
       [29., 18., 90.],
       [54., 84., 31.]], dtype=float32)>

In [31]:
da = tf.matmul(d,a)
da

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[24983., 19749., 13106.],
       [19749., 21005., 11126.],
       [13106., 11126., 13026.]], dtype=float32)>

In [41]:
a = tf.constant([[1,2],
                 [3,4]], dtype = tf.int32)
b = tf.Variable([[1,2],
                 [3,4]])

da1 = tf.multiply(a,b)
da1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]])>

In [53]:
r, c = da.shape
print('Rows:',r,
     'Columns:',c)

Rows: 3 Columns: 3


In [52]:
# Identity Matrix
im = tf.eye(3, dtype = tf.int32)
im

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])>

In [65]:
import random
t_s = []
t_l = []
for i in range(50):
    r_y = random.randint(13, 64)
    t_s.append(r_y)
    t_l.append(1)
    r_o = random.randint(65,100)
    t_s.append(r_o)
    t_l.append(0)

In [67]:
t_s

[25,
 97,
 33,
 82,
 64,
 98,
 38,
 81,
 59,
 78,
 44,
 89,
 52,
 86,
 39,
 84,
 18,
 87,
 21,
 77,
 17,
 68,
 19,
 88,
 37,
 94,
 53,
 71,
 16,
 75,
 21,
 73,
 63,
 80,
 40,
 86,
 54,
 96,
 27,
 70,
 23,
 85,
 17,
 79,
 53,
 73,
 38,
 71,
 21,
 84,
 59,
 70,
 35,
 72,
 30,
 75,
 41,
 86,
 37,
 73,
 16,
 72,
 26,
 91,
 34,
 74,
 30,
 82,
 24,
 72,
 61,
 74,
 26,
 70,
 31,
 84,
 53,
 75,
 56,
 92,
 63,
 74,
 56,
 93,
 62,
 89,
 61,
 85,
 44,
 65,
 21,
 86,
 44,
 92,
 46,
 70,
 22,
 71,
 47,
 96]

In [68]:
t_l

[1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0]